---
# defaults file

workdir: ~/ocp4-workdir
log_level: info
release_image_override: ""

# IBM/Red Hat QE Only: Disables ClusterImagePolicy so Nightly builds can be deployed. This feature puts a cluster in unsupported mode.
qe_only_disable_image_policy: false
storage_type: none
